[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["*"]
gas_reports_ignore = ["test/**", "script/**"]
evm_version = "istanbul"

[profile.ci]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["*"]
gas_reports_ignore = ["test/**", "script/**"]
fuzz = { runs = 1000 }
invariant = { runs = 10, depth = 15 }
optimizer = true
optimizer_runs = 200

[profile.coverage]
src = "src"
out = "out"
libs = ["lib"]
fuzz = { runs = 1000 }
invariant = { runs = 10, depth = 15 }

[profile.release]
optimizer = true
optimizer_runs = 10_000_000
