[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["*"]
gas_reports_ignore = ["test/**", "script/**"]

[profile.ci]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["*"]
gas_reports_ignore = ["test/**", "script/**"]
fuzz = { runs = 1000 }
invariant = { runs = 10, depth = 15 }
optimizer = true
optimizer_runs = 200

[profile.coverage]
src = "src"
out = "out"
libs = ["lib"]
fuzz = { runs = 1000 }
invariant = { runs = 10, depth = 15 }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
